/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.app.demo

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = "Hello"

        when:
        def result = "Hello"

        then:
        result == "Hello"
    }
}
